# Generated by Django 6.0 on 2026-01-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Physical Education', 'Physical Education'), ('Arts', 'Arts'), ('Others', 'Others')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('joining_date', models.DateField()),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('experience', models.IntegerField(default=0, help_text='Years of experience')),
                ('address', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
