# Generated by Django 6.0 on 2026-01-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='FP1MwGjdNQSQ8WUm0ukQ5WR3UNFtW6yt', editable=False, max_length=100, unique=True),
        ),
    ]
