# Generated by Django 6.0 on 2026-01-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0moTb1gpJHWWOwspdTLGTkgAaOFys5vA', editable=False, max_length=100, unique=True),
        ),
    ]
