# Generated by Django 6.0 on 2026-01-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
