# Generated by Django 6.0 on 2026-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
